### Overview of cell types

Short description of the central brain cell types and their corresponding scRNA clusters

* 3 main families: Glia - Neurons (OL/CB)  & devel?

* Overview of the data available by cell type

* A "card" for each cell type with the summary of info? 
    (Can also include the info on the table)
    - selected motifs/TFs?
    - information on how they were annotated
    - validation (ex. for KCs)
    
* Refer to the paper for details? (or vice-versa? :) )

<details><summary> Table description</summary>

Has information about the different clusters/cell types, e.g. correspondence across datasets (RNA-ATAC), & within clusterings (e.g. different granularity within ATAC), it also has some notes from Jasper (e.g. neurotransmitter, whether it is glia/neuron… & some clarifications, such as "confidence level", which cell types it might include [some are not just one cell type], or what was used to annotate it [e.g. specific marker]...)

Relevant columns?: 
- Cell type/ Cluster (full name)
- Description
- Certainty
- Neurotransmitter 
- 'ID' in RNA and ATAC datasets

We could also provide the list of cell IDs per cluster

</details>

More info: 
- Table of differential [regions](https://fbdapp.aertslab.org/test/FBD_App/?_inputs_&page=%22Nw_Tables%22) and [genes](https://fbdapp.aertslab.org/test/FBD_App/?_inputs_&page=%22Nw_Tables%22).
- Overview [Key regulators](https://fbdapp.aertslab.org/test/FBD_App/?_inputs_&page=%22Nw_CellTypeTFs%22&Nw_CellTypeTFs-tab=%22dotplots%22)
