#### RNA markers

<details><summary>[+] <i>Description</i></summary>

Gene expression in adult cell types (markers and gene detection). Only contains the cell types matched to ATAC.

**Markers**: Adult cell type markers

*Columns:*

- `Cluster`: Cluster/cell type name

- `isTF`: Whether the gene is annotated as transcription factor

- `pct.diff`: Difference in percentage detection between the given cluster and the rest of cells

- `Gene`, `p_val_adj` (adjusted p-value), `avg_logFC` (average fold change), `pct.1`, `pct.2` (percentage of detection in the cluster and remaining cells): Values calculated with Seurat for the given Gene and Cell type

**Genes detected**: Genes detected in cell types (RNA). 

*Columns:* 

- `cellType` and `gene`

- `perc`: Percentage of total cells in the cluster with expression bigger than 0.

- `cnt`: Number of cells in the cluster with expression bigger than 0.

Network version: 1.0 (Aug. 2021); Table last updated on Feb. 2020.

[[Download table](downloads/other/tbl_RNAmarkers.txt.zip)]
</details>

